### ISSUE TITLE
Translation with param

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-vuejs#171]
Translation with param are not used.

For example, `home.json` :

```yaml
{
  "home": {
    "title": "Bienvenue, Java Hipster !",
    "subtitle": "Ceci est votre page d'accueil",
    "logged": {
      "message": "Vous êtes connecté en tant que \"{{username}}\"."
    },
    "question": "Si vous avez des questions à propos de JHipster :",
    "link": {
      "homepage": "Page d'accueil de JHipster",
      "stackoverflow": "JHipster sur Stack Overflow",
      "bugtracker": "JHipster bug tracker",
      "chat": "JHipster public chat room",
      "follow": "Suivez @java_hipster sur Twitter"
    },
    "like": "Si vous aimez JHipster, donnez nous une étoile sur",
    "github": "GitHub "
  }
}
```

After authentication, the message should be: `Vous êtes connecté en tant que "admin".`
But the following message is displayed: `You are logged in as user "admin".`

Not sure but I think it's because it's hard coded here: https://github.com/jhipster/jhipster-vuejs/blob/master/generators/client/templates/vue/src/main/webapp/app/core/home/home.vue.ejs#L12
