### ISSUE TITLE
Reset password

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-vuejs#238]
The reset password workflow doesn't work:
- in the form, the email is always invalid
- then, the link http://127.0.0.1:8080/#/reset/finish?key=45180041592469282639 doesn't exist

**Comment by pascalgrimaud** [comment]
I'm trying to have a look.
If someone wants to help, you can use this docker-compose file, to start a local smtp server (I used my own module https://github.com/pascalgrimaud/generator-jhipster-docker)

```yaml
version: '2'
services:
    smtp:
        image: djfarrelly/maildev
        ports:
            - 1080:80
            - "25:25"
```
